---
title: "XAI3: Model-agnostic methods. Partial Dependency Plot (PDP)."
author: "Group 21: Yassmina Jebbour Maamri & Qilu Diana Wu"
output: html_notebook
---

## 0.- Introduction.

```{r}
setwd(".")

list.of.packages <- c("reshape2", "dplyr", "caret", "ggplot2", "tidyr", "ROCR", "plotly", "randomForest", "party", "pdp")
new.packages <- list.of.packages[!(list.of.packages %in% installed.packages()[,"Package"])]
if(length(new.packages)) install.packages(new.packages)
lapply(list.of.packages, require, character.only=TRUE)
```

## 1.- One dimensional Partial Dependence Plot.

```{r}
day <- read.csv("day.csv")

# Use one-hot encoding for season
day$season <- as.factor(day$season)
one_hot_encoded <- dummyVars(" ~ season", data = day)
new_season <- predict(one_hot_encoded, newdata = day)
day <- cbind(day, new_season)

# Create feature MISTY
MISTY <- as.data.frame(ifelse(day$weathersit == 2, 1, 0))
colnames(MISTY) <- "MISTY"
day <- cbind(day, MISTY)

# Create feature RAIN
RAIN <- as.data.frame(ifelse(day$weathersit == 3 | day$weathersit == 4, 1, 0))
colnames(RAIN) <- "RAIN"
day <- cbind(day, RAIN)

# Denormalize temp
# temp: Normalized temperature in Celsius. The values are derived via
# (t-t_min)/(t_max-t_min), t_min=-8, t_max=+39 (only in hourly scale)
t_min = -8
t_max = +39
new_temp <- day$temp * (t_max-t_min) + t_min
day <- cbind(day, new_temp)

# Denormalize hum
# hum: Normalized humidity. The values are divided to 100 (max)
new_hum <- day$hum * 100
day <- cbind(day, new_hum)

# Denormalize windspeed
# windspeed: Normalized wind speed. The values are divided to 67 (max)
new_windspeed <- day$windspeed * 67
day <- cbind(day, new_windspeed)

# Create feature days_since_2011
days_since_2011 <- difftime(as.Date(day$dteday), as.Date("2011-01-01"), units = "days")
days_since_2011 <- as.data.frame(as.numeric(days_since_2011))
colnames(days_since_2011) <- "days_since_2011"
day <- cbind(day, days_since_2011)

# Select features that will be used in the linear model
# Only select 3 features for season to avoid correlation (season.1 as reference)
day <- subset(day, select = c(workingday, holiday, season.2, season.3, season.4, MISTY, 
                              RAIN, new_temp, new_hum, new_windspeed, days_since_2011, cnt))

# Rename features
# season (1:winter, 2:spring, 3:summer, 4:fall)
colnames(day)[3] <- "spring"
colnames(day)[4] <- "summer"
colnames(day)[5] <- "fall"
colnames(day)[8] <- "temp"
colnames(day)[9] <- "hum"
colnames(day)[10] <- "windspeed"

# Ajustar el modelo de Random Forest
set.seed(250)
rf_model <- randomForest(cnt ~ ., data = day, importance = TRUE)

# Generar Partial Dependence Plots para todas las variables
variables <- names(day)
variables <- variables[variables != "cnt"] 

for (var in variables) {
  partial_obj <- partial(rf_model, pred.var = var, prob = TRUE, chull = TRUE, progress = TRUE, plot = TRUE, rug = TRUE, 
                         plot.engine = "ggplot2",  plot_args = list(geom = c("line", "density"))) + xlab(var) + 
    ylab("Predicted number of bike rentals")
  # plot.engine = "ggplot2",  plot_args = list(geom = c("line", "density"))
  print(partial_obj) # Esto es necesario para mostrar los gráficos cuando se usa en un script
}
```
